// <auto-generated />
namespace DDD.WinForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deletemaker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletemaker));
        
        string IMigrationMetadata.Id
        {
            get { return "202003090008028_deletemaker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
